// whisperedcloud/job-portal/Job-portal-a4e6f3febf7c2af1c6b0ae3caeec2fd6d7878031/src/integrations/supabase/client.ts

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Replace these values with your new project's credentials
const SUPABASE_URL = "https://yzppfbsoarvaodfncpjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6cHBmYnNvYXJ2YW9kZm5jcGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMzYyMjUsImV4cCI6MjA3NDgxMjIyNX0.vpzRvaQF3TOtkWN2E4q1ZwIJ_bUzWOj-hD958XxgHEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);